include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

stages:
  - check
  - test
  - deploy

variables:
  BUNDLE: "org.gnome.GtranslatorDevel.flatpak"

flatpak:
  extends: .flatpak
  variables:
    GIT_SUBMODULE_STRATEGY: normal

    # Replace with your manifest path
    MANIFEST_PATH: "build-aux/flatpak/org.gnome.Gtranslator.json"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
    # Replace with your application name, as written in the manifest
    FLATPAK_MODULE: "gtranslator"
    APP_ID: "org.gnome.GtranslatorDevel"

nightly:
  extends: '.publish_nightly'
  dependencies:
    - 'flatpak'

# Lint the code
clang-format:
  stage: check
  image: fedora:36
  script:
    - dnf install -y clang-tools-extra git
    - git fetch --depth 50 origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME:$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - git diff -U0 --no-color --relative $CI_MERGE_REQUEST_TARGET_BRANCH_NAME | scripts/check-diff-style.sh
  only:
    - merge_requests
