include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

stages:
  - test
  - review
  - deploy

variables:
  BUNDLE: "org.gnome.GtranslatorDevel.flatpak"

flatpak:
  extends: .flatpak
  variables:
    GIT_SUBMODULE_STRATEGY: normal

    # Replace with your manifest path
    MANIFEST_PATH: "build-aux/flatpak/org.gnome.Gtranslator.json"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
    # Replace with your application name, as written in the manifest
    FLATPAK_MODULE: "gtranslator"
    APP_ID: "org.gnome.GtranslatorDevel"

review:
  extends: .review
  dependencies:
    - flatpak

stop_review:
  extends: .stop_review

nightly:
  extends: '.publish_nightly'
  dependencies:
    - 'flatpak'
