---
stages:
  - test
  - review

variables:
  BUNDLE: "org.gnome.Gtranslator.flatpak"
  MANIFEST_PATH: "build-aux/flatpak/org.gnome.Gtranslator.json"
  FLATPAK_MODULE: "gtranslator"
  DBUS_ID: "org.gnome.Gtranslator"

.flatpak_cache_template: &flatpak_cache
  cache:
    key: "flatpak"
    paths:
      - .flatpak-builder/cache/

flatpak:
  image: "registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:3.30"
  stage: "test"
  script:
    - flatpak-builder --stop-at=${FLATPAK_MODULE} --force-clean app ${MANIFEST_PATH}

    # Build the flatpak repo
    - flatpak-builder --run app ${MANIFEST_PATH} meson --prefix=/app _build
    - flatpak-builder --run app ${MANIFEST_PATH} ninja -C _build install

    # Create a flatpak bundle
    - flatpak-builder --finish-only app ${MANIFEST_PATH}
    - flatpak build-export repo app
    - flatpak build-bundle repo ${BUNDLE} ${DBUS_ID}

  artifacts:
    paths:
      - "${BUNDLE}"
    expire_in: 30 days
  <<: *flatpak_cache

review:
  stage: review
  dependencies:
    - flatpak
  script:
    - echo "Generating flatpak deployment"
  artifacts:
    paths:
      - ${BUNDLE}
    expire_in: 30 days
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://gitlab.gnome.org/$CI_PROJECT_PATH/-/jobs/$CI_JOB_ID/artifacts/raw/${BUNDLE}
    on_stop: stop_review
  except:
    - master@GNOME/gtranslator
    - tags

stop_review:
  stage: review
  script:
    - echo "Stopping flatpak deployment"
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  except:
    - master@GNOME/gtranslator
    - tags