ignore = [
    "_build/**",
    "tests/**",
    "subprojects/**",
    ".foundry/**",
]

min_glib_version = "2.76"
msvc_compatible = false

[rules]
no_g_auto_macros = "ignore"
property_enum_convention = "ignore"
