ignore = [
    "_build/**",
    "tests/**",
    "subprojects/**",
    ".foundry/**",
]

min_glib_version = "2.76"
msvc_compatible = false

[rules.type_style]
style = "c"

[rules.property_enum_convention]
style = "legacy"
