/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("gtranslator -- beginner's druid");
gchar *s = N_("gtranslator's beginner's druid -- welcome!");
gchar *s = N_("Welcome to the gtranslator setup druid which will help you to\n"
              "setup gtranslator easily through some questions and help you\n"
              "starting to work with gtranslator.\n"
              "\n"
              "Fatih Demir/kabalak/kabalak@gmx.net");
gchar *s = N_("gtranslator's beginner's druid -- data acquirement");
gchar *s = N_("Your language:");
gchar *s = N_("Your EMail address:");
gchar *s = N_("How much featurism is wished?");
gchar *s = N_("Update the po-revision date automatically?");
gchar *s = N_("Your name");
gchar *s = N_("Your name:");
gchar *s = N_("Your EMail address");
gchar *s = N_("Hypris! I wanna see it all!\n"
              "Normal level -- not too many stuff please\n"
              "Almost nothing please\n"
              "");
gchar *s = N_("Hypris! I wanna see it all!");
gchar *s = N_("Yes");
gchar *s = N_("No");
gchar *s = N_("gtranslator's beginner's druid says: we're done.");
gchar *s = N_("The wise druid says: we're done :-)\n"
              "\n"
              "Hopefully this is true...");
