/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Open a po-file");
gchar *s = N_("Filename: ");
gchar *s = N_("File size:   ");
gchar *s = N_("Last edit: ");
gchar *s = N_("Revision: ");
