/* Automatically generated by po2tbl.sed from gtranslator.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"_Compile", 2},
  {"Refresh", 3},
  {"_First", 4},
  {"_Back", 5},
  {"_Next", 6},
  {"_Last", 7},
  {"_Online help", 8},
  {"_Messages", 9},
  {"gtranslator", 10},
  {"Compile", 11},
  {"New File", 12},
  {"Open", 13},
  {"Open File", 14},
  {"Save", 15},
  {"Save File", 16},
  {"Save as", 17},
  {"First", 18},
  {"Back", 19},
  {"Options", 20},
  {"Next", 21},
  {"Last", 22},
  {"Exit", 23},
  {"(C) 1999-2000 Fatih Demir ( kabalak@gmx.net )", 24},
  {"\
gtranslator is a GnomeApplication for translating .po-files more comfortable \
than in (X)Emacs .\n\
Till now you can't see much , but that will change !", 25},
  {"Warn me if there are errors in the .po-file", 26},
  {"Ask for saving unchanged .po-files ", 27},
  {"gtranslator should start at the last edited file", 28},
  {"Common settings ", 29},
  {"Show me the output of msgfmt --statistics", 30},
  {"Don't  show me any messages of msgfmt ", 31},
  {"Compiling  points ...", 32},
  {"Select your .po-file to open", 33},
  {"Select your file to save to", 34},
  {"\
An error occured in your .po-file as it \n\
couldn't be compiled by mfgfmt !", 35},
  {"\
You try to save an unchanged .po-file !\n\
How useless .", 36},
  {"\
Your .po-file is being compiled by \n\
msgfmt now ....", 37},
  {"\
Please wait for the help system .\n\
( I'd to learn going along with gtkxmhtml ..)", 38},
  {"\
Here you can select various options of\n\
gtranslator which will make gtranslator\n\
more work like you want it to .", 39},
  {"Saving file ...", 40},
  {"Open a .po-file first !", 41},
  {"Getting the next ...", 42},
  {"Happy translation !", 43},
  {"Inited reading process .", 44},
  {"Reading now msgid's ...", 45},
  {"Couldn't find pixmap file: %s", 46},
  {"Couldn't create pixmap from file: %s", 47},
  {"The msgids will appear here .", 48},
  {"Your translation goes here .", 49},
  {"\
gtranslator is a GnomeApplication for translation .po-files more comfortable \
than in (X)Emacs .", 50},
};

int _msg_tbl_length = 50;
