/* Automatically generated by po2tbl.sed from gtranslator.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"_Compile", 2},
  {"Refresh", 3},
  {"_First", 4},
  {"_Back", 5},
  {"_Next", 6},
  {"_Last", 7},
  {"_Online help", 8},
  {"_Messages", 9},
  {"gtranslator", 10},
  {"Search", 11},
  {"Search for a message", 12},
  {"ReSearch", 13},
  {"Search again", 14},
  {"Goto", 15},
  {"Goto this message", 16},
  {"F/Cat.", 17},
  {"Find in the personal catalog", 18},
  {"F/Po.", 19},
  {"Find in the po file ", 20},
  {"Compile", 21},
  {"New File", 22},
  {"Open", 23},
  {"Open File", 24},
  {"Save", 25},
  {"Save File", 26},
  {"Save as", 27},
  {"First", 28},
  {"Back", 29},
  {"Options", 30},
  {"Next", 31},
  {"Last", 32},
  {"Exit", 33},
  {"(C) 1999-2000 Fatih Demir ( kabalak@gmx.net )", 34},
  {"\
gtranslator is a GnomeApplication for translating .po-files more comfortable \
than in (X)Emacs .\n\
Till now you can't see much , but that will change !", 35},
  {"Warn me if there are errors in the .po-file", 36},
  {"Ask for saving unchanged .po-files ", 37},
  {"gtranslator should start at the last edited file", 38},
  {"Common settings ", 39},
  {"Show me the output of msgfmt --statistics", 40},
  {"Don't  show me any messages of msgfmt ", 41},
  {"Compiling  points ...", 42},
  {"Select your .po-file to open", 43},
  {"Select your file to save to", 44},
  {"\
An error occured in your .po-file as it \n\
couldn't be compiled by mfgfmt !", 45},
  {"\
You try to save an unchanged .po-file !\n\
How useless .", 46},
  {"\
Your .po-file is being compiled by \n\
msgfmt now ....", 47},
  {"\
Here you can select various options of\n\
gtranslator which will make gtranslator\n\
more work like you want it to .", 48},
  {"Saving file ...", 49},
  {"Open a .po-file first !", 50},
  {"You're already at the first translatable string !", 51},
  {"No .po-file is opened at the moment !", 52},
  {"You are at the first translatable string !", 53},
  {"File has been changed !", 54},
  {"Happy translation !", 55},
  {"Couldn't find pixmap file: %s", 56},
  {"Couldn't create pixmap from file: %s", 57},
};

int _msg_tbl_length = 57;
