/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gnome.h>

#include "beginners-druid-functions.h"
#include "beginners-druid-interface.h"
#include "support.h"

GtkWidget*
create_gtranslator_druid (void)
{
  GtkWidget *gtranslator_druid;
  GtkWidget *gtranslator_druid_druid;
  GtkWidget *gtranslator_druid_welcome_page;
  GdkColor gtranslator_druid_welcome_page_bg_color = { 0, 6425, 6425, 28784 };
  GdkColor gtranslator_druid_welcome_page_textbox_color = { 0, 65535, 65535, 65535 };
  GdkColor gtranslator_druid_welcome_page_logo_bg_color = { 0, 65278, 65278, 65278 };
  GdkColor gtranslator_druid_welcome_page_title_color = { 0, 65535, 65535, 65535 };
  GtkWidget *gtranslator_druid_get_data_page;
  GdkColor gtranslator_druid_get_data_page_bg_color = { 0, 6425, 6425, 28784 };
  GdkColor gtranslator_druid_get_data_page_logo_bg_color = { 0, 65535, 65535, 65535 };
  GdkColor gtranslator_druid_get_data_page_title_color = { 0, 65535, 65535, 65535 };
  GtkWidget *druid_vbox1;
  GtkWidget *data_area;
  GtkWidget *language_label;
  GtkWidget *email_label;
  GtkWidget *featurism_level_label;
  GtkWidget *autoset_date_label;
  GtkWidget *name_entry;
  GtkWidget *name_label;
  GtkWidget *entry3;
  GtkWidget *featurism_combo_box;
  GList *featurism_combo_box_items = NULL;
  GtkWidget *combo_entry1;
  GSList *auto_update_group_group = NULL;
  GtkWidget *featurism_yes_radio_button;
  GtkWidget *featurism_no_radio_button;
  GtkWidget *labguage_combo_box;
  GtkWidget *combo_entry2;
  GtkWidget *gtranslator_druid_finish;
  GdkColor gtranslator_druid_finish_bg_color = { 0, 6425, 6425, 28784 };
  GdkColor gtranslator_druid_finish_textbox_color = { 0, 65535, 65535, 65535 };
  GdkColor gtranslator_druid_finish_logo_bg_color = { 0, 65535, 65535, 65535 };
  GdkColor gtranslator_druid_finish_title_color = { 0, 65535, 65535, 65535 };

  gtranslator_druid = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (gtranslator_druid, "gtranslator_druid");
  gtk_object_set_data (GTK_OBJECT (gtranslator_druid), "gtranslator_druid", gtranslator_druid);
  gtk_window_set_title (GTK_WINDOW (gtranslator_druid), _("gtranslator -- beginner's druid"));
  gtk_window_set_policy (GTK_WINDOW (gtranslator_druid), TRUE, FALSE, FALSE);
  gtk_window_set_wmclass (GTK_WINDOW (gtranslator_druid), "gtranslator", "gtranslator");

  gtranslator_druid_druid = gnome_druid_new ();
  gtk_widget_set_name (gtranslator_druid_druid, "gtranslator_druid_druid");
  gtk_widget_ref (gtranslator_druid_druid);
  gtk_object_set_data_full (GTK_OBJECT (gtranslator_druid), "gtranslator_druid_druid", gtranslator_druid_druid,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (gtranslator_druid_druid);
  gtk_container_add (GTK_CONTAINER (gtranslator_druid), gtranslator_druid_druid);

  gtranslator_druid_welcome_page = gnome_druid_page_start_new ();
  gtk_widget_set_name (gtranslator_druid_welcome_page, "gtranslator_druid_welcome_page");
  gtk_widget_ref (gtranslator_druid_welcome_page);
  gtk_object_set_data_full (GTK_OBJECT (gtranslator_druid), "gtranslator_druid_welcome_page", gtranslator_druid_welcome_page,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (gtranslator_druid_welcome_page);
  gnome_druid_append_page (GNOME_DRUID (gtranslator_druid_druid), GNOME_DRUID_PAGE (gtranslator_druid_welcome_page));
  gnome_druid_set_page (GNOME_DRUID (gtranslator_druid_druid), GNOME_DRUID_PAGE (gtranslator_druid_welcome_page));
  gnome_druid_page_start_set_bg_color (GNOME_DRUID_PAGE_START (gtranslator_druid_welcome_page), &gtranslator_druid_welcome_page_bg_color);
  gnome_druid_page_start_set_textbox_color (GNOME_DRUID_PAGE_START (gtranslator_druid_welcome_page), &gtranslator_druid_welcome_page_textbox_color);
  gnome_druid_page_start_set_logo_bg_color (GNOME_DRUID_PAGE_START (gtranslator_druid_welcome_page), &gtranslator_druid_welcome_page_logo_bg_color);
  gnome_druid_page_start_set_title_color (GNOME_DRUID_PAGE_START (gtranslator_druid_welcome_page), &gtranslator_druid_welcome_page_title_color);
  gnome_druid_page_start_set_title (GNOME_DRUID_PAGE_START (gtranslator_druid_welcome_page), _("gtranslator's beginner's druid -- welcome!"));
  gnome_druid_page_start_set_text (GNOME_DRUID_PAGE_START (gtranslator_druid_welcome_page), _("Welcome to the gtranslator setup druid which will help you to\nsetup gtranslator easily through some questions and help you\nstarting to work with gtranslator.\n\nFatih Demir/kabalak/kabalak@gmx.net"));

  gtranslator_druid_get_data_page = gnome_druid_page_standard_new_with_vals ("", NULL);
  gtk_widget_set_name (gtranslator_druid_get_data_page, "gtranslator_druid_get_data_page");
  gtk_widget_ref (gtranslator_druid_get_data_page);
  gtk_object_set_data_full (GTK_OBJECT (gtranslator_druid), "gtranslator_druid_get_data_page", gtranslator_druid_get_data_page,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show_all (gtranslator_druid_get_data_page);
  gnome_druid_append_page (GNOME_DRUID (gtranslator_druid_druid), GNOME_DRUID_PAGE (gtranslator_druid_get_data_page));
  gnome_druid_page_standard_set_bg_color (GNOME_DRUID_PAGE_STANDARD (gtranslator_druid_get_data_page), &gtranslator_druid_get_data_page_bg_color);
  gnome_druid_page_standard_set_logo_bg_color (GNOME_DRUID_PAGE_STANDARD (gtranslator_druid_get_data_page), &gtranslator_druid_get_data_page_logo_bg_color);
  gnome_druid_page_standard_set_title_color (GNOME_DRUID_PAGE_STANDARD (gtranslator_druid_get_data_page), &gtranslator_druid_get_data_page_title_color);
  gnome_druid_page_standard_set_title (GNOME_DRUID_PAGE_STANDARD (gtranslator_druid_get_data_page), _("gtranslator's beginner's druid -- data acquirement"));

  druid_vbox1 = GNOME_DRUID_PAGE_STANDARD (gtranslator_druid_get_data_page)->vbox;
  gtk_widget_set_name (druid_vbox1, "druid_vbox1");
  gtk_widget_ref (druid_vbox1);
  gtk_object_set_data_full (GTK_OBJECT (gtranslator_druid), "druid_vbox1", druid_vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (druid_vbox1);

  data_area = gtk_fixed_new ();
  gtk_widget_set_name (data_area, "data_area");
  gtk_widget_ref (data_area);
  gtk_object_set_data_full (GTK_OBJECT (gtranslator_druid), "data_area", data_area,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (data_area);
  gtk_box_pack_start (GTK_BOX (druid_vbox1), data_area, TRUE, TRUE, 0);

  language_label = gtk_label_new (_("Your language:"));
  gtk_widget_set_name (language_label, "language_label");
  gtk_widget_ref (language_label);
  gtk_object_set_data_full (GTK_OBJECT (gtranslator_druid), "language_label", language_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (language_label);
  gtk_fixed_put (GTK_FIXED (data_area), language_label, -1, -1);
  gtk_widget_set_uposition (language_label, 72, 96);
  gtk_widget_set_usize (language_label, 120, 16);

  email_label = gtk_label_new (_("Your EMail address:"));
  gtk_widget_set_name (email_label, "email_label");
  gtk_widget_ref (email_label);
  gtk_object_set_data_full (GTK_OBJECT (gtranslator_druid), "email_label", email_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (email_label);
  gtk_fixed_put (GTK_FIXED (data_area), email_label, -1, -1);
  gtk_widget_set_uposition (email_label, 72, 64);
  gtk_widget_set_usize (email_label, 120, 16);

  featurism_level_label = gtk_label_new (_("How much featurism is wished?"));
  gtk_widget_set_name (featurism_level_label, "featurism_level_label");
  gtk_widget_ref (featurism_level_label);
  gtk_object_set_data_full (GTK_OBJECT (gtranslator_druid), "featurism_level_label", featurism_level_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (featurism_level_label);
  gtk_fixed_put (GTK_FIXED (data_area), featurism_level_label, -1, -1);
  gtk_widget_set_uposition (featurism_level_label, 40, 128);
  gtk_widget_set_usize (featurism_level_label, 152, 16);

  autoset_date_label = gtk_label_new (_("Update the po-revision date automatically?"));
  gtk_widget_set_name (autoset_date_label, "autoset_date_label");
  gtk_widget_ref (autoset_date_label);
  gtk_object_set_data_full (GTK_OBJECT (gtranslator_druid), "autoset_date_label", autoset_date_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (autoset_date_label);
  gtk_fixed_put (GTK_FIXED (data_area), autoset_date_label, -1, -1);
  gtk_widget_set_uposition (autoset_date_label, 8, 160);
  gtk_widget_set_usize (autoset_date_label, 200, 16);

  name_entry = gtk_entry_new ();
  gtk_widget_set_name (name_entry, "name_entry");
  gtk_widget_ref (name_entry);
  gtk_object_set_data_full (GTK_OBJECT (gtranslator_druid), "name_entry", name_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (name_entry);
  gtk_fixed_put (GTK_FIXED (data_area), name_entry, -1, -1);
  gtk_widget_set_uposition (name_entry, 248, 32);
  gtk_widget_set_usize (name_entry, 158, 20);
  gtk_entry_set_text (GTK_ENTRY (name_entry), _("Your name"));

  name_label = gtk_label_new (_("Your name:"));
  gtk_widget_set_name (name_label, "name_label");
  gtk_widget_ref (name_label);
  gtk_object_set_data_full (GTK_OBJECT (gtranslator_druid), "name_label", name_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (name_label);
  gtk_fixed_put (GTK_FIXED (data_area), name_label, -1, -1);
  gtk_widget_set_uposition (name_label, 72, 32);
  gtk_widget_set_usize (name_label, 120, 16);

  entry3 = gtk_entry_new ();
  gtk_widget_set_name (entry3, "entry3");
  gtk_widget_ref (entry3);
  gtk_object_set_data_full (GTK_OBJECT (gtranslator_druid), "entry3", entry3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (data_area), entry3, -1, -1);
  gtk_widget_set_uposition (entry3, 248, 64);
  gtk_widget_set_usize (entry3, 158, 20);
  gtk_entry_set_text (GTK_ENTRY (entry3), _("Your EMail address"));

  featurism_combo_box = gtk_combo_new ();
  gtk_widget_set_name (featurism_combo_box, "featurism_combo_box");
  gtk_widget_ref (featurism_combo_box);
  gtk_object_set_data_full (GTK_OBJECT (gtranslator_druid), "featurism_combo_box", featurism_combo_box,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (featurism_combo_box);
  gtk_fixed_put (GTK_FIXED (data_area), featurism_combo_box, -1, -1);
  gtk_widget_set_uposition (featurism_combo_box, 248, 128);
  gtk_widget_set_usize (featurism_combo_box, 175, 20);
  gtk_combo_set_value_in_list (GTK_COMBO (featurism_combo_box), TRUE, TRUE);
  featurism_combo_box_items = g_list_append (featurism_combo_box_items, _("Hypris! I wanna see it all!"));
  featurism_combo_box_items = g_list_append (featurism_combo_box_items, _("Normal level -- not too many stuff please"));
  featurism_combo_box_items = g_list_append (featurism_combo_box_items, _("Almost nothing please"));
  gtk_combo_set_popdown_strings (GTK_COMBO (featurism_combo_box), featurism_combo_box_items);
  g_list_free (featurism_combo_box_items);

  combo_entry1 = GTK_COMBO (featurism_combo_box)->entry;
  gtk_widget_set_name (combo_entry1, "combo_entry1");
  gtk_widget_ref (combo_entry1);
  gtk_object_set_data_full (GTK_OBJECT (gtranslator_druid), "combo_entry1", combo_entry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry1);
  gtk_entry_set_text (GTK_ENTRY (combo_entry1), _("Hypris! I wanna see it all!"));

  featurism_yes_radio_button = gtk_radio_button_new_with_label (auto_update_group_group, _("Yes"));
  auto_update_group_group = gtk_radio_button_group (GTK_RADIO_BUTTON (featurism_yes_radio_button));
  gtk_widget_set_name (featurism_yes_radio_button, "featurism_yes_radio_button");
  gtk_widget_ref (featurism_yes_radio_button);
  gtk_object_set_data_full (GTK_OBJECT (gtranslator_druid), "featurism_yes_radio_button", featurism_yes_radio_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (featurism_yes_radio_button);
  gtk_fixed_put (GTK_FIXED (data_area), featurism_yes_radio_button, -1, -1);
  gtk_widget_set_uposition (featurism_yes_radio_button, 248, 160);
  gtk_widget_set_usize (featurism_yes_radio_button, 84, 22);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (featurism_yes_radio_button), TRUE);

  featurism_no_radio_button = gtk_radio_button_new_with_label (auto_update_group_group, _("No"));
  auto_update_group_group = gtk_radio_button_group (GTK_RADIO_BUTTON (featurism_no_radio_button));
  gtk_widget_set_name (featurism_no_radio_button, "featurism_no_radio_button");
  gtk_widget_ref (featurism_no_radio_button);
  gtk_object_set_data_full (GTK_OBJECT (gtranslator_druid), "featurism_no_radio_button", featurism_no_radio_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (featurism_no_radio_button);
  gtk_fixed_put (GTK_FIXED (data_area), featurism_no_radio_button, -1, -1);
  gtk_widget_set_uposition (featurism_no_radio_button, 336, 160);
  gtk_widget_set_usize (featurism_no_radio_button, 84, 22);

  labguage_combo_box = gtk_combo_new ();
  gtk_widget_set_name (labguage_combo_box, "labguage_combo_box");
  gtk_widget_ref (labguage_combo_box);
  gtk_object_set_data_full (GTK_OBJECT (gtranslator_druid), "labguage_combo_box", labguage_combo_box,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (labguage_combo_box);
  gtk_fixed_put (GTK_FIXED (data_area), labguage_combo_box, -1, -1);
  gtk_widget_set_uposition (labguage_combo_box, 248, 96);
  gtk_widget_set_usize (labguage_combo_box, 175, 20);
  gtk_combo_set_value_in_list (GTK_COMBO (labguage_combo_box), TRUE, TRUE);

  combo_entry2 = GTK_COMBO (labguage_combo_box)->entry;
  gtk_widget_set_name (combo_entry2, "combo_entry2");
  gtk_widget_ref (combo_entry2);
  gtk_object_set_data_full (GTK_OBJECT (gtranslator_druid), "combo_entry2", combo_entry2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry2);

  gtranslator_druid_finish = gnome_druid_page_finish_new ();
  gtk_widget_set_name (gtranslator_druid_finish, "gtranslator_druid_finish");
  gtk_widget_ref (gtranslator_druid_finish);
  gtk_object_set_data_full (GTK_OBJECT (gtranslator_druid), "gtranslator_druid_finish", gtranslator_druid_finish,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (gtranslator_druid_finish);
  gnome_druid_append_page (GNOME_DRUID (gtranslator_druid_druid), GNOME_DRUID_PAGE (gtranslator_druid_finish));
  gnome_druid_page_finish_set_bg_color (GNOME_DRUID_PAGE_FINISH (gtranslator_druid_finish), &gtranslator_druid_finish_bg_color);
  gnome_druid_page_finish_set_textbox_color (GNOME_DRUID_PAGE_FINISH (gtranslator_druid_finish), &gtranslator_druid_finish_textbox_color);
  gnome_druid_page_finish_set_logo_bg_color (GNOME_DRUID_PAGE_FINISH (gtranslator_druid_finish), &gtranslator_druid_finish_logo_bg_color);
  gnome_druid_page_finish_set_title_color (GNOME_DRUID_PAGE_FINISH (gtranslator_druid_finish), &gtranslator_druid_finish_title_color);
  gnome_druid_page_finish_set_title (GNOME_DRUID_PAGE_FINISH (gtranslator_druid_finish), _("gtranslator's beginner's druid says: we're done."));
  gnome_druid_page_finish_set_text (GNOME_DRUID_PAGE_FINISH (gtranslator_druid_finish), _("The wise druid says: we're done :-)\n\nHopefully this is true..."));

  gtk_signal_connect (GTK_OBJECT (gtranslator_druid), "delete_event",
                      GTK_SIGNAL_FUNC (gtk_widget_hide),
                      gtranslator_druid);
  gtk_signal_connect (GTK_OBJECT (gtranslator_druid), "destroy_event",
                      GTK_SIGNAL_FUNC (gtk_widget_hide),
                      gtranslator_druid);
  gtk_signal_connect (GTK_OBJECT (gtranslator_druid_druid), "cancel",
                      GTK_SIGNAL_FUNC (gtk_widget_hide),
                      gtranslator_druid);
  gtk_signal_connect (GTK_OBJECT (gtranslator_druid_finish), "cancel",
                      GTK_SIGNAL_FUNC (gtk_widget_hide),
                      gtranslator_druid);
  gtk_signal_connect (GTK_OBJECT (gtranslator_druid_finish), "finish",
                      GTK_SIGNAL_FUNC (gtranslator_druid_finish),
                      NULL);

  return gtranslator_druid;
}

