/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gnome.h>

#include "open-po-file-dialog-functions.h"
#include "open-po-file-dialog-interface.h"

GtkWidget*
create_open_po_file_dialog (void)
{
  GtkWidget *open_po_file_dialog;
  GtkWidget *vbox1;
  GtkWidget *hpaned1;
  GtkWidget *file_tree;
  GtkWidget *vbox2;
  GtkWidget *mime_icon;
  GtkWidget *vbox3;
  GtkWidget *hbox1;
  GtkWidget *label1;
  GtkWidget *file_name;
  GtkWidget *hbox2;
  GtkWidget *label2;
  GtkWidget *file_size;
  GtkWidget *hbox4;
  GtkWidget *label3;
  GtkWidget *last_change;
  GtkWidget *hbox5;
  GtkWidget *label4;
  GtkWidget *po_version;
  GtkWidget *hbuttonbox2;
  GtkWidget *ok_button;
  GtkWidget *reopen_last_button;
  GtkWidget *cancel_button;

  open_po_file_dialog = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (open_po_file_dialog, "open_po_file_dialog");
  gtk_object_set_data (GTK_OBJECT (open_po_file_dialog), "open_po_file_dialog", open_po_file_dialog);
  gtk_window_set_title (GTK_WINDOW (open_po_file_dialog), _("Open a po-file"));
  gtk_window_set_wmclass (GTK_WINDOW (open_po_file_dialog), "gtranslator", "gtranslator");

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (open_po_file_dialog), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (open_po_file_dialog), vbox1);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_set_name (hpaned1, "hpaned1");
  gtk_widget_ref (hpaned1);
  gtk_object_set_data_full (GTK_OBJECT (open_po_file_dialog), "hpaned1", hpaned1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hpaned1);
  gtk_box_pack_start (GTK_BOX (vbox1), hpaned1, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (hpaned1), 0);

  file_tree = gtk_tree_new ();
  gtk_widget_set_name (file_tree, "file_tree");
  gtk_widget_ref (file_tree);
  gtk_object_set_data_full (GTK_OBJECT (open_po_file_dialog), "file_tree", file_tree,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file_tree);
  gtk_paned_pack1 (GTK_PANED (hpaned1), file_tree, FALSE, TRUE);

  vbox2 = gtk_vbox_new (TRUE, 0);
  gtk_widget_set_name (vbox2, "vbox2");
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (open_po_file_dialog), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_paned_pack2 (GTK_PANED (hpaned1), vbox2, TRUE, TRUE);

  mime_icon = gtk_type_new (gnome_pixmap_get_type ());
  gtk_widget_set_name (mime_icon, "mime_icon");
  gtk_widget_ref (mime_icon);
  gtk_object_set_data_full (GTK_OBJECT (open_po_file_dialog), "mime_icon", mime_icon,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mime_icon);
  gtk_box_pack_start (GTK_BOX (vbox2), mime_icon, TRUE, TRUE, 0);

  vbox3 = gtk_vbox_new (TRUE, 0);
  gtk_widget_set_name (vbox3, "vbox3");
  gtk_widget_ref (vbox3);
  gtk_object_set_data_full (GTK_OBJECT (open_po_file_dialog), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (vbox2), vbox3, TRUE, TRUE, 0);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox1, "hbox1");
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (open_po_file_dialog), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox1, TRUE, TRUE, 0);

  label1 = gtk_label_new (_("Filename: "));
  gtk_widget_set_name (label1, "label1");
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (open_po_file_dialog), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label1), GTK_JUSTIFY_LEFT);

  file_name = gtk_entry_new ();
  gtk_widget_set_name (file_name, "file_name");
  gtk_widget_ref (file_name);
  gtk_object_set_data_full (GTK_OBJECT (open_po_file_dialog), "file_name", file_name,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file_name);
  gtk_box_pack_start (GTK_BOX (hbox1), file_name, TRUE, TRUE, 0);
  gtk_entry_set_editable (GTK_ENTRY (file_name), FALSE);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox2, "hbox2");
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (open_po_file_dialog), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox2, TRUE, TRUE, 0);

  label2 = gtk_label_new (_("File size:   "));
  gtk_widget_set_name (label2, "label2");
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (open_po_file_dialog), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label2), GTK_JUSTIFY_RIGHT);

  file_size = gtk_entry_new ();
  gtk_widget_set_name (file_size, "file_size");
  gtk_widget_ref (file_size);
  gtk_object_set_data_full (GTK_OBJECT (open_po_file_dialog), "file_size", file_size,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file_size);
  gtk_box_pack_start (GTK_BOX (hbox2), file_size, TRUE, TRUE, 0);
  gtk_entry_set_editable (GTK_ENTRY (file_size), FALSE);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox4, "hbox4");
  gtk_widget_ref (hbox4);
  gtk_object_set_data_full (GTK_OBJECT (open_po_file_dialog), "hbox4", hbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox4, TRUE, TRUE, 0);

  label3 = gtk_label_new (_("Last edit: "));
  gtk_widget_set_name (label3, "label3");
  gtk_widget_ref (label3);
  gtk_object_set_data_full (GTK_OBJECT (open_po_file_dialog), "label3", label3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox4), label3, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_LEFT);

  last_change = gtk_entry_new ();
  gtk_widget_set_name (last_change, "last_change");
  gtk_widget_ref (last_change);
  gtk_object_set_data_full (GTK_OBJECT (open_po_file_dialog), "last_change", last_change,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (last_change);
  gtk_box_pack_start (GTK_BOX (hbox4), last_change, TRUE, TRUE, 0);
  gtk_entry_set_editable (GTK_ENTRY (last_change), FALSE);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox5, "hbox5");
  gtk_widget_ref (hbox5);
  gtk_object_set_data_full (GTK_OBJECT (open_po_file_dialog), "hbox5", hbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox5, TRUE, TRUE, 0);

  label4 = gtk_label_new (_("Revision: "));
  gtk_widget_set_name (label4, "label4");
  gtk_widget_ref (label4);
  gtk_object_set_data_full (GTK_OBJECT (open_po_file_dialog), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox5), label4, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label4), GTK_JUSTIFY_LEFT);

  po_version = gtk_entry_new ();
  gtk_widget_set_name (po_version, "po_version");
  gtk_widget_ref (po_version);
  gtk_object_set_data_full (GTK_OBJECT (open_po_file_dialog), "po_version", po_version,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (po_version);
  gtk_box_pack_start (GTK_BOX (hbox5), po_version, TRUE, TRUE, 0);
  gtk_entry_set_editable (GTK_ENTRY (po_version), FALSE);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox2, "hbuttonbox2");
  gtk_widget_ref (hbuttonbox2);
  gtk_object_set_data_full (GTK_OBJECT (open_po_file_dialog), "hbuttonbox2", hbuttonbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), hbuttonbox2, TRUE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox2), GTK_BUTTONBOX_SPREAD);

  ok_button = gnome_stock_button (GNOME_STOCK_BUTTON_OK);
  gtk_widget_set_name (ok_button, "ok_button");
  gtk_widget_ref (ok_button);
  gtk_object_set_data_full (GTK_OBJECT (open_po_file_dialog), "ok_button", ok_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (ok_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), ok_button);
  GTK_WIDGET_SET_FLAGS (ok_button, GTK_CAN_DEFAULT);

  reopen_last_button = gnome_stock_button (GNOME_STOCK_BUTTON_PREV);
  gtk_widget_set_name (reopen_last_button, "reopen_last_button");
  gtk_widget_ref (reopen_last_button);
  gtk_object_set_data_full (GTK_OBJECT (open_po_file_dialog), "reopen_last_button", reopen_last_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (reopen_last_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), reopen_last_button);
  GTK_WIDGET_SET_FLAGS (reopen_last_button, GTK_CAN_DEFAULT);

  cancel_button = gnome_stock_button (GNOME_STOCK_BUTTON_CANCEL);
  gtk_widget_set_name (cancel_button, "cancel_button");
  gtk_widget_ref (cancel_button);
  gtk_object_set_data_full (GTK_OBJECT (open_po_file_dialog), "cancel_button", cancel_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cancel_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), cancel_button);
  GTK_WIDGET_SET_FLAGS (cancel_button, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (open_po_file_dialog), "delete_event",
                      GTK_SIGNAL_FUNC (gtk_widget_hide),
                      open_po_file_dialog);
  gtk_signal_connect (GTK_OBJECT (open_po_file_dialog), "destroy_event",
                      GTK_SIGNAL_FUNC (gtk_widget_hide),
                      open_po_file_dialog);
  gtk_signal_connect (GTK_OBJECT (file_tree), "select_child",
                      GTK_SIGNAL_FUNC (file_tree_select_child),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (file_tree), "unselect_child",
                      GTK_SIGNAL_FUNC (file_tree_unselect_child),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (file_tree), "selection_changed",
                      GTK_SIGNAL_FUNC (file_tree_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (ok_button), "clicked",
                      GTK_SIGNAL_FUNC (open_po_file),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (reopen_last_button), "clicked",
                      GTK_SIGNAL_FUNC (reopen_last_po_file),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (cancel_button), "clicked",
                      GTK_SIGNAL_FUNC (gtk_widget_hide),
                      open_po_file_dialog);

  return open_po_file_dialog;
}

