/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gnome.h>

#include "preferences-functions.h"
#include "preferences-interface.h"

GtkWidget*
create_gtranslator_preferences_dialog (void)
{
  GtkWidget *gtranslator_preferences_dialog;
  GtkWidget *preferences_dialog_area;
  GtkWidget *preferences_pane;
  GtkWidget *preferences_index_scrolled_window;
  GtkWidget *index;
  GtkWidget *index_sections_label;
  GtkWidget *preferences_buttons;
  GtkWidget *apply_button;
  GtkWidget *ok_button;
  GtkWidget *cancel_button;

  gtranslator_preferences_dialog = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (gtranslator_preferences_dialog, "gtranslator_preferences_dialog");
  gtk_object_set_data (GTK_OBJECT (gtranslator_preferences_dialog), "gtranslator_preferences_dialog", gtranslator_preferences_dialog);
  gtk_widget_set_usize (gtranslator_preferences_dialog, 480, 300);
  gtk_window_set_title (GTK_WINDOW (gtranslator_preferences_dialog), _("gtranslator -- preferences"));
  gtk_window_set_wmclass (GTK_WINDOW (gtranslator_preferences_dialog), "gtranslator", "gtranslator");

  preferences_dialog_area = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (preferences_dialog_area, "preferences_dialog_area");
  gtk_widget_ref (preferences_dialog_area);
  gtk_object_set_data_full (GTK_OBJECT (gtranslator_preferences_dialog), "preferences_dialog_area", preferences_dialog_area,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (preferences_dialog_area);
  gtk_container_add (GTK_CONTAINER (gtranslator_preferences_dialog), preferences_dialog_area);

  preferences_pane = gtk_hpaned_new ();
  gtk_widget_set_name (preferences_pane, "preferences_pane");
  gtk_widget_ref (preferences_pane);
  gtk_object_set_data_full (GTK_OBJECT (gtranslator_preferences_dialog), "preferences_pane", preferences_pane,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (preferences_pane);
  gtk_box_pack_start (GTK_BOX (preferences_dialog_area), preferences_pane, TRUE, TRUE, 0);
  gtk_paned_set_handle_size (GTK_PANED (preferences_pane), 8);
  gtk_paned_set_gutter_size (GTK_PANED (preferences_pane), 4);
  gtk_paned_set_position (GTK_PANED (preferences_pane), 160);

  preferences_index_scrolled_window = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (preferences_index_scrolled_window, "preferences_index_scrolled_window");
  gtk_widget_ref (preferences_index_scrolled_window);
  gtk_object_set_data_full (GTK_OBJECT (gtranslator_preferences_dialog), "preferences_index_scrolled_window", preferences_index_scrolled_window,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (preferences_index_scrolled_window);
  gtk_paned_pack1 (GTK_PANED (preferences_pane), preferences_index_scrolled_window, FALSE, TRUE);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (preferences_index_scrolled_window), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  index = gtk_clist_new (1);
  gtk_widget_set_name (index, "index");
  gtk_widget_ref (index);
  gtk_object_set_data_full (GTK_OBJECT (gtranslator_preferences_dialog), "index", index,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (index);
  gtk_container_add (GTK_CONTAINER (preferences_index_scrolled_window), index);
  gtk_clist_set_column_width (GTK_CLIST (index), 0, 148);
  gtk_clist_column_titles_show (GTK_CLIST (index));

  index_sections_label = gtk_label_new (_("Sections"));
  gtk_widget_set_name (index_sections_label, "index_sections_label");
  gtk_widget_ref (index_sections_label);
  gtk_object_set_data_full (GTK_OBJECT (gtranslator_preferences_dialog), "index_sections_label", index_sections_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (index_sections_label);
  gtk_clist_set_column_widget (GTK_CLIST (index), 0, index_sections_label);

  preferences_buttons = gtk_hbutton_box_new ();
  gtk_widget_set_name (preferences_buttons, "preferences_buttons");
  gtk_widget_ref (preferences_buttons);
  gtk_object_set_data_full (GTK_OBJECT (gtranslator_preferences_dialog), "preferences_buttons", preferences_buttons,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (preferences_buttons);
  gtk_box_pack_start (GTK_BOX (preferences_dialog_area), preferences_buttons, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (preferences_buttons), GTK_BUTTONBOX_SPREAD);
  gtk_button_box_set_child_size (GTK_BUTTON_BOX (preferences_buttons), 32, 16);
  gtk_button_box_set_child_ipadding (GTK_BUTTON_BOX (preferences_buttons), 2, 0);

  apply_button = gnome_stock_button (GNOME_STOCK_BUTTON_APPLY);
  gtk_widget_set_name (apply_button, "apply_button");
  gtk_widget_ref (apply_button);
  gtk_object_set_data_full (GTK_OBJECT (gtranslator_preferences_dialog), "apply_button", apply_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (apply_button);
  gtk_container_add (GTK_CONTAINER (preferences_buttons), apply_button);
  GTK_WIDGET_SET_FLAGS (apply_button, GTK_CAN_DEFAULT);

  ok_button = gnome_stock_button (GNOME_STOCK_BUTTON_OK);
  gtk_widget_set_name (ok_button, "ok_button");
  gtk_widget_ref (ok_button);
  gtk_object_set_data_full (GTK_OBJECT (gtranslator_preferences_dialog), "ok_button", ok_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (ok_button);
  gtk_container_add (GTK_CONTAINER (preferences_buttons), ok_button);
  GTK_WIDGET_SET_FLAGS (ok_button, GTK_CAN_DEFAULT);

  cancel_button = gnome_stock_button (GNOME_STOCK_BUTTON_CANCEL);
  gtk_widget_set_name (cancel_button, "cancel_button");
  gtk_widget_ref (cancel_button);
  gtk_object_set_data_full (GTK_OBJECT (gtranslator_preferences_dialog), "cancel_button", cancel_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cancel_button);
  gtk_container_add (GTK_CONTAINER (preferences_buttons), cancel_button);
  GTK_WIDGET_SET_FLAGS (cancel_button, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (gtranslator_preferences_dialog), "delete_event",
                      GTK_SIGNAL_FUNC (gtranslator_preferences_quit),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (gtranslator_preferences_dialog), "destroy_event",
                      GTK_SIGNAL_FUNC (gtranslator_preferences_quit),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (index), "select_row",
                      GTK_SIGNAL_FUNC (index_row_is_selected),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (index), "click_column",
                      GTK_SIGNAL_FUNC (index_clicked_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (index), "unselect_all",
                      GTK_SIGNAL_FUNC (index_nothing_selected),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (apply_button), "clicked",
                      GTK_SIGNAL_FUNC (preferences_apply),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (ok_button), "clicked",
                      GTK_SIGNAL_FUNC (preferences_ok),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (cancel_button), "clicked",
                      GTK_SIGNAL_FUNC (gtranslator_preferences_quit),
                      NULL);

  return gtranslator_preferences_dialog;
}

